
apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-check-sa
  namespace: health-checks
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager-role
  namespace: health-checks
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"] # Needed to find the pod associated with a job
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: health-check-binding
  namespace: health-checks
subjects:
  - kind: ServiceAccount
    name: health-check-sa
    namespace: health-checks
roleRef:
  kind: Role
  name: job-manager-role
  apiGroup: rbac.authorization.k8s.io